### ISSUE TITLE
DDT took more than 2 minutes for searching a query

### ISSUE THREAD

**Issue by kienpt** [VIDA-NYU/domain_discovery_tool#21]
I created a new domain called "Generative Adversarial Networks", then searched the following query using Google API: "GANs network". DDT keeps showing "searching: gans network" for more than 2 minutes. DDT behaves the same if I repeat searching for the same query. Also, users can't scroll down the search result list while DDT is searching.
Here is the log:

org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:305)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:200)
	at org.elasticsearch.client.transport.support.InternalTransportClient.execute(InternalTransportClient.java:106)
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:334)
	at org.elasticsearch.client.transport.TransportClient.search(TransportClient.java:416)
	at org.elasticsearch.action.search.SearchRequestBuilder.doExecute(SearchRequestBuilder.java:1122)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
	at Download_URL.run(Download_URL.java:233)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Time Elapsed time for https://ctovision.com/generative-adversary-networks-track-artificial-intelligence-critical-understand/ thread = 147.098 secs 

{'query': u'gans network'}

**Comment by sheeluee7** [comment]
I also faced the same issue, it takes a lot of time on query & I also got same logs. Unable to scroll when DDT is scrolling is really frustrating.

**Comment by julianafreire** [comment]
@yamsgithub can you please look into this?

**Comment by yamsgithub** [comment]
@sheeluee7 I will see if I can reproduce the problem. Can you please provide the query you were using? But it may take me couple of weeks to get to resolving it as we have some deadlines. Will try to get to it earlier if I get the chance.
