### ISSUE TITLE
Java ClassNotFoundException when starting crawl

### ISSUE THREAD

**Issue by ayoungprogrammer** [VIDA-NYU/domain_discovery_tool#65]
I am running docker compose on docker-compose.yml.ache.

I started a focused crawl from a model built from DDT using approx 100 relevant and 100 irrelevant labels and got the following error.

```
ache_1           | java.lang.IllegalArgumentException: Failed to load smile classifier instance from file: /config/cyber_model/pageclassifier.model
ache_1           | 	at focusedCrawler.util.SmileUtil.loadSmileClassifier(SmileUtil.java:24)
ache_1           | 	at focusedCrawler.target.classifier.SmileTargetClassifier.create(SmileTargetClassifier.java:141)
ache_1           | 	at focusedCrawler.target.classifier.SmileTargetClassifier.create(SmileTargetClassifier.java:114)
ache_1           | 	at focusedCrawler.target.classifier.TargetClassifierFactory.create(TargetClassifierFactory.java:80)
ache_1           | 	at focusedCrawler.target.TargetStorage.create(TargetStorage.java:128)
ache_1           | 	at focusedCrawler.crawler.async.AsyncCrawler.create(AsyncCrawler.java:117)
ache_1           | 	at focusedCrawler.crawler.CrawlersManager.createCrawler(CrawlersManager.java:104)
ache_1           | 	at focusedCrawler.Main$StartCrawl.run(Main.java:246)
ache_1           | 	at focusedCrawler.Main.main(Main.java:59)
ache_1           | Caused by: java.lang.ClassNotFoundException: weka.classifiers.functions.SMO
```

**Comment by yamsgithub** [comment]
@ayoungprogrammer I updated the docker after updating the ache version we were using. You should no longer see this issue. Please let us know if it is otherwise.
